### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Maokei** [Maokei/mserver#69]
# Dashboard

There should be a dashboard view / layout after logging in so we don't go straight to the player.

## TODO:

- Dashboard layout (initial dashboard layout) figma allowed too
- Redirect to dashboard view / component after login

## Branch 
master_dashboard

**Comment by BlenderWang** [comment]
![Image](https://user-images.githubusercontent.com/19404426/180211787-165ba2f6-3c11-4a22-ae59-c6ab93dbc92e.jpg)
![Image](https://user-images.githubusercontent.com/19404426/180211786-20f26009-8896-49da-9976-59fca83b8c08.jpg)
